services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/data
      - /mnt/plex/Library:/data/music
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - MUSIC_PATH=/data/music/demo/
      - MUSIC2_PATH=/data/music/mp3/
      - USE_FFMPEG=true
      - HLS_ENABLED=true

volumes:
  data:
